# See https://embarkstudios.github.io/cargo-deny/cli/init.html
# for details on these configuration options.

[advisories]
version = 2
yanked = "warn"
ignore = [
    "RUSTSEC-2020-0071",
    "RUSTSEC-2023-0052",
    "RUSTSEC-2023-0005",
    "RUSTSEC-2025-0023",
    "RUSTSEC-2025-0010",
    "RUSTSEC-2024-0336",
    "RUSTSEC-2025-0009",
    "RUSTSEC-2024-0370",
    "RUSTSEC-2024-0019",
    "RUSTSEC-2024-0384",
    "RUSTSEC-2024-0421",
    "RUSTSEC-2023-0034",
    "RUSTSEC-2024-0003",
    "RUSTSEC-2024-0332",
    "RUSTSEC-2024-0388",
    "RUSTSEC-2022-0078"
]

[licenses]
version = 2
allow = [
    "MIT",
    "Apache-2.0",
    # You can safely enable these licenses if needed:
    # "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "OpenSSL",
    "Unicode-DFS-2016"
]

# The `ring` crate has a complicated license situation with different licenses
# for different parts of the codebase, but they're all acceptable to us.
# If you need the `ring` crate then uncomment the below.
[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[licenses.private]
# So we don't have to declare a license on our own unpublished crates.
ignore = true

[bans]
multiple-versions = "warn"
wildcards = "warn"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
