version: '3.7'
services:

  cargo:
    image: harrisonai/rust:1.60-0.2
    entrypoint: cargo
    volumes:
      - '~/.cargo/registry:/usr/local/cargo/registry'
      - '~/.cargo/advisory-dbs:/usr/local/cargo/advisory-dbs'
      - '~/.cargo/git/db:/usr/local/cargo/git/db'
      - '.:/app'
    working_dir: '/app'

  shellcheck:
    image: koalaman/shellcheck:v0.8.0
    volumes:
      - '.:/app'
    working_dir: '/app'

  localstack:
    image: localstack/localstack:1.0.3
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
      - "127.0.0.1:53:53"                # DNS config (only required for Pro)
      - "127.0.0.1:53:53/udp"            # DNS config (only required for Pro)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway (only required for Pro)
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}  # only required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=ap-southeast-2
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/init-localstack.sh:/docker-entrypoint-initaws.d/init-localstack.sh"
      - "./test-data:/tmp/test-data"
